### ISSUE TITLE
Pregunta: Problemas con Recibir Parámetros

### ISSUE THREAD

**Issue by Paguila** [clsource/prestashop-webpay#21]
Estoy tratando de implementar este modulo pero me salta una error. Seria de gran ayuda si me das una mano con esto.
![image](https://cloud.githubusercontent.com/assets/7363102/11247887/cf9b2c88-8dfc-11e5-8e7b-08a6bc059c02.png)

Los archivos de log que tengo tiran esto:

2015-11-18 09:33:46 : Start Validation
2015-11-18 09:33:46 : #################
2015-11-18 09:33:46 : Params Not Found
2015-11-18 09:33:46 : TBK_ORDEN_COMPRA Not Set
2015-11-18 09:33:46 : TBK_RESPUESTA not set
2015-11-18 09:33:46 : Final Result: RECHAZADO
2015-11-18 09:33:46 : End Validation
2015-11-18 09:33:46 : #################

y otro dice:

2522800;257

Para la prueba estoy usando estos datos encontrado en un pagina

VISA: 4051885600446623 (Resultado Aprobado)
Mastercard: 5186059559590568 (Resultado Rechazado)
Código Verificación: 123
Fecha vencimiento: 01/2018
RUT: 11.111.111-1
Clave: 123

Me quedo esperando una respuesta que pueda salvarme hahaha, Saludos

**Comment by clsource** [comment]
Según el Log 

```
2015-11-18 09:33:46 : Params Not Found
```

No se están recibiendo los parámetros correctamente.
prueba usando postman https://chrome.google.com/webstore/detail/postman/fhbjgbiflinjbdggehcddcbncdddomop

para enviar los parámetros al script y ver cómo los recibe.

**Comment by Paguila** [comment]
![image](https://cloud.githubusercontent.com/assets/7363102/11249210/51b36dc8-8e04-11e5-9054-61abb742175a.png)

![image](https://cloud.githubusercontent.com/assets/7363102/11249230/6dff45f6-8e04-11e5-8f90-f692ab5a4da7.png)

![image](https://cloud.githubusercontent.com/assets/7363102/11249237/74d34cba-8e04-11e5-9d16-d236856dd35d.png)

Esos datos obtuve..No se si serán los que pedías. Me quedo atento a cualquier cosa

**Comment by clsource** [comment]
ee creo que no xd.

Sigue estos pasos:

- 1 ) Compra un nuevo producto
- 2) Antes de iniciar el formulario de transbank revisa los datos enviados por medio de post en el formulario de la tienda (ver código fuente)
- 3) Envía esos datos al archivo validate.php de tu tienda (https://github.com/clsource/prestashop-webpay/blob/master/webpaykcc/validate.php) usando postman

**Comment by Paguila** [comment]
![image](https://cloud.githubusercontent.com/assets/7363102/11249449/a8f8ffa2-8e05-11e5-8d8d-9214b3f05827.png)

Esto? Disculpa por lo lento. Nunca había visto esta aplicación. Saludos

**Comment by clsource** [comment]
Envía esos parámetros al archivo validate.php
y revisa los logs :)

**Comment by clsource** [comment]
También deberías revisar los logs creados por transbank en /cgi-bin/log tal vez den más información sobre por qué no se recibieron los parámetros :+1:

**Comment by Paguila** [comment]
![image](https://cloud.githubusercontent.com/assets/7363102/11249616/c4b3bf4c-8e06-11e5-87b2-2ae79f99492d.png)

El log no dice mucho

**Comment by clsource** [comment]
mmm eso es raro.
primero prueba creando la tienda en el dominio raíz (sin estar dentro de un subdirectorio).

luego verifica que los archivos del kcc no estén corruptos.
prueba subiéndolos como zip y luego descomprimirlos en el servidor.

**Comment by Paguila** [comment]
Moví los archivos con filezilla para no tener problemas pero sale el mismo error. ¿Como le envió esos los datos a validate.php? Eso no he probado. Saludos.

PE: No puedo cambiar a la raíz del servidor. Está siendo ocupado para otros fines

**Comment by Paguila** [comment]
Es necesario el archivo xt_compra? Donde lo tengo que dejar?

**Comment by clsource** [comment]
creo que esto es problema de que el kcc está corrupto.
por favor sube los archivos comprimidos en zip y luego los descomprimes dentro del servidor. 
verifica que tengan permisos 755.

para enviar los datos utiliza postman y pon la ruta completa hacia validate.php (la misma usada en la configuración de transbank).

**Comment by Paguila** [comment]
![image](https://cloud.githubusercontent.com/assets/7363102/11250715/90bcf2de-8e0c-11e5-892a-cda2d60bc43e.png)

Volví descomprimí los archivos en el servidor y nada...probé enviando los datos y me salio eso. Saludos

**Comment by clsource** [comment]
¿qué dicen los logs?

**Comment by Paguila** [comment]
Hola

Realmente tenia problemas con el servidor. Muy probable que sea el firewall que se usa en la empresa. El problema que tengo ahora es que siempre me sale la pestaña de rechazo.

![image](https://cloud.githubusercontent.com/assets/7363102/11342721/89ef4b26-91e7-11e5-8ac7-997c369c2e9a.png)

El log de KCC me envia esto

![image](https://cloud.githubusercontent.com/assets/7363102/11342801/d4d88da0-91e7-11e5-8eec-4b1073cf40b8.png)

y el log del xt_compra me tira esto 

![image](https://cloud.githubusercontent.com/assets/7363102/11342902/4ce25f56-91e8-11e5-89f7-68c45ecd86fa.png)

el codigo de xt_compra que estoy usando lo saqué de uno de tus docs

![image](https://cloud.githubusercontent.com/assets/7363102/11342930/6a9e99a6-91e8-11e5-8928-5f3f38a36766.png)

Saludos,

**Comment by clsource** [comment]
hola ese código no tiene nada que ver con el plugin
ese es el código de ejemplo que entrega transbank y no debe ser usado.

tienes que apuntar al script validation.php que viene en el plugin
saludos.

**Comment by Paguila** [comment]
Ahora me di cuenta...sorry Pero leyendo en internet me sale que hay problemas con el KCC y los servidores linux

**Comment by clsource** [comment]
hace poco valide una tienda en linux y el kcc.
verifica que tienes la arquitectura correcta. :)

**Comment by Paguila** [comment]
Hola nuevamente...ya solucione el tema en el servidor de producción(con win) pero sigo teniendo el error 46

![image](https://cloud.githubusercontent.com/assets/7363102/11376866/c5439422-92c1-11e5-99e6-252e2439cba8.png)

Lo que enuentro raro es que busca el "tbk_check_mac.cgi" siendo que el kit de windows no lo incorpora.

Saludos!

**Comment by clsource** [comment]
no he probado el script en servidores windows, 
solamente en linux.

la version gratuita usa exec

https://github.com/clsource/prestashop-webpay/blob/master/webpaykcc/validate.php#L257

pero la versión de pago no, 
junto con unos script de perl para hacer de puente.

**Comment by clsource** [comment]
para cambiar el nombre del script modifica este archivo

https://github.com/clsource/prestashop-webpay/blob/master/webpaykcc/lib-webpaykcc/constants.php#L52

**Comment by Paguila** [comment]
Quieres ser el padrino de mis hijos? hahaha
Tu modulo está perfecto el problema principal era entre la silla y el computador. Voy a tratar de actualizar algunas características. Cualquier avance te lo señalo por si te interesa verlo. Saludos

**Comment by clsource** [comment]
capa 8?
jajaj xdd

**Comment by clsource** [comment]
bueno me alegro que lo hayas solucionado.
entonces cerraré este issue y me cuentas

saludos :)
