### ISSUE TITLE
Webservice

### ISSUE THREAD

**Issue by Paguila** [clsource/prestashop-webpay#22]
Hola,

Tienes algún manual para integrar webpay server webservice... en la pega contrataron ese servicio y creo que no lo comprendo muy bien. Saludos!

**Comment by clsource** [comment]
Hola, 
acá está 
https://github.com/clsource/guia-webpay/tree/master/webpay-soap/webpay-oneclick

pero esta incompleta, 
ya que no me financiaron más el proyecto.

dicen que en http://www.transbankdevelopers.cl/
hay más información sobre la cosa.
:+1:
