### ISSUE TITLE
Failed CGI Verification

### ISSUE THREAD

**Issue by agrass** [clsource/prestashop-webpay#23]
Estoy teniendo un error que falla al momento de ejecutar el tbk_check_mac.cgi. Que podrá ser?
Es un servidor bien básico que lo puedo administrar por cpanel nomas, no tengo acceso a consola. El ip del servidor no permite entrar directamente a la app ya que hay varias apps en ese mismo ip, tiene que tener el dominio osino rutea a otra pagina del host. No se si afecte esto, de todos modos le puse el ip que me dio haciendo ``` ping -c1 dominio.com```. 

Alguien se le ocurre que puede ser lo que pueda estar fallando? Adjunto imágenes con más detalles del error.

![selection_532](https://cloud.githubusercontent.com/assets/1148266/13082085/e73ad512-d4ad-11e5-979d-675e56d3e683.png)

![selection_533](https://cloud.githubusercontent.com/assets/1148266/13082093/ea619dca-d4ad-11e5-85ab-6aabc1cdba58.png)

![selection_534](https://cloud.githubusercontent.com/assets/1148266/13082095/ed421a24-d4ad-11e5-8f19-cee1c9ef4431.png)

Saludos y gracias de antemano

**Comment by clsource** [comment]
Hola, 
Según los logs dicen que todo va bien
hasta la validación por CGI que arroja null.

Esto puede deberse a que no existe la función exec

https://github.com/clsource/prestashop-webpay/blob/master/webpaykcc/validate.php#L257

verifica que exista en tu server :)

saludos

**Comment by agrass** [comment]
Hola Camilo, 

Gracias por tu respuesta! Ahí logre hacerlo funcionar, efectivamente había que activar el exec agregando un php.ini con ``` disable_functions = ``` donde se hacia el exec.

Saludos, y muchas gracias por tu iluminación
